repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.1
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, clickhouse, --config, .sqlfluff]
        additional_dependencies:
          - sqlfluff-templater-dbt==3.1.1
          - dbt-core==1.8.7
          - dbt-clickhouse==1.8.7
      - id: sqlfluff-fix
        args: [--dialect, clickhouse, --config, .sqlfluff]
        additional_dependencies:
          - sqlfluff-templater-dbt==3.1.1
          - dbt-core==1.8.7
          - dbt-clickhouse==1.8.7
